# Generated by Django 5.0.4 on 2024-05-07 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_remove_rental_rental_amount_remove_rental_penalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.discounts'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='penalty',
            field=models.ManyToManyField(null=True, to='cars.penalties'),
        ),
    ]
