# Generated by Django 5.1.1 on 2024-09-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_employeecontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeContact',
        ),
    ]
