# Generated by Django 5.0.4 on 2024-05-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_regular_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_firts_time',
            field=models.BooleanField(default=True, verbose_name='is_firts_time'),
        ),
    ]
