# Generated by Django 5.0.4 on 2024-05-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='images/no.jpg', upload_to='images/', verbose_name='Загрузите аватар для машины'),
        ),
    ]
