# Generated by Django 5.1.1 on 2024-09-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='penalties',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
