# Generated by Django 5.0.4 on 2024-05-04 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='rental',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.discounts'),
        ),
        migrations.AddField(
            model_name='rental',
            name='penalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.penalties'),
        ),
        migrations.AddField(
            model_name='sales',
            name='rental',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.rental'),
        ),
    ]
