# Generated by Django 5.0.4 on 2024-05-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penalties',
            old_name='amount',
            new_name='percentage',
        ),
    ]
