# Generated by Django 5.0.4 on 2024-05-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_bodytype_name_alter_car_license_plate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rental_amount',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='penalty',
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='rental',
            name='penalty',
            field=models.ManyToManyField(to='cars.penalties'),
        ),
    ]
