# Generated by Django 5.0.4 on 2024-05-07 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_rental_discount_alter_rental_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.discounts'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='penalty',
            field=models.ManyToManyField(blank=True, null=True, to='cars.penalties'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.promocode'),
        ),
    ]
