# Generated by Django 5.0.4 on 2024-05-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_rental_discount_alter_rental_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_pass',
            field=models.BooleanField(default=False, verbose_name='is_pass'),
        ),
    ]
