# Generated by Django 5.0.4 on 2024-05-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_rental_is_pass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
