# Generated by Django 5.0.4 on 2024-05-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_car_created_at_car_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
