# Generated by Django 5.0.4 on 2024-05-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='images/no.jpg', null=True, upload_to='images/', verbose_name='Загрузите аватар для машины'),
        ),
    ]
