# Generated by Django 5.0.4 on 2024-05-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='images/no.jpg', null=True, upload_to='images/', verbose_name='Загрузите аватар для машины'),
        ),
    ]
