# Generated by Django 5.0.4 on 2024-05-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_rename_amount_penalties_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='promocode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.promocode'),
        ),
    ]
