# Generated by Django 5.0.4 on 2024-05-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_promocode_rental_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='penalties',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='penalties',
            name='percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.IntegerField(),
        ),
    ]
