version: '3'

services:
  react-app:
    build: ./client
    container_name: react-app
    restart: always
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - mern-app

  api-server:
    build: ./server
    container_name: api-server
    restart: always
    ports:
      - 5001:5001
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-app

volumes:
  mongo-data:
    driver: local

networks:
  mern-app:
    driver: bridge
