# Generated by Django 5.0.4 on 2024-05-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_firts_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_firts_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_regular_customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_firts_time',
            field=models.BooleanField(default=True, verbose_name='is_firts_time'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_regular_customer',
            field=models.BooleanField(default=False, verbose_name='is_regular_customer'),
        ),
    ]
