# Generated by Django 5.1.1 on 2024-10-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_slidersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidersettings',
            name='auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='loop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='navs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='pags',
            field=models.BooleanField(default=True),
        ),
    ]
