# Generated by Django 5.1.1 on 2024-09-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_vacancy_payment_vacancy_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='employees/')),
                ('description', models.TextField()),
            ],
        ),
    ]
