# Generated by Django 5.1.1 on 2024-10-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_delete_employeecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='url',
            field=models.URLField(default='https://example.com'),
        ),
    ]
