# Generated by Django 5.1.1 on 2024-10-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_employee_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='url',
            field=models.URLField(),
        ),
    ]
