# Generated by Django 5.1.1 on 2024-09-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_newsarticle_time_create_newsarticle_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='payment',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
